server:
  port: 8080

---

spring:
  config:
    activate:
      on-profile: local-db
postgresql:
  datasource:
    driver-class-name: org.postgresql.Driver
    jdbc-url: jdbc:postgresql://localhost:15432/bogudb
    username: flower
    password: ffdb

---
